#!/usr/bin/env bash
set -euo pipefail

SDK_ROOT="${SDK_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
WEBRTC_PREFIX="${WEBRTC_PREFIX:-${SDK_ROOT}/dist/linux-x86_64}"
OUTPUT_DIR="${OUTPUT_DIR:-${SDK_ROOT}/artifacts/webrtc_first_qoe_high_complexity_720p}"

FRAMES="${FRAMES:-60}"
WIDTH="${WIDTH:-1280}"
HEIGHT="${HEIGHT:-720}"
START_BITRATE_BPS="${START_BITRATE_BPS:-1800000}"
MIN_BITRATE_BPS="${MIN_BITRATE_BPS:-300000}"
MAX_BITRATE_BPS="${MAX_BITRATE_BPS:-3000000}"
MIN_PLAYABLE_RATIO="${MIN_PLAYABLE_RATIO:-0.75}"
MIN_AVG_PSNR_Y="${MIN_AVG_PSNR_Y:-15.0}"
MIN_AVG_SSIM_Y="${MIN_AVG_SSIM_Y:-0.55}"
MAX_WEAK_SEND_RPS="${MAX_WEAK_SEND_RPS:-15.0}"
MAX_WEAK_RTP_PPS="${MAX_WEAK_RTP_PPS:-240.0}"
MAX_WEAK_TARGET_BPS="${MAX_WEAK_TARGET_BPS:-900000}"
MAX_WEAK_ENCODER_FPS="${MAX_WEAK_ENCODER_FPS:-10}"
MAX_RECOVERY_TIME_MS="${MAX_RECOVERY_TIME_MS:-1000}"
RENDERER_PROXY_TARGET_DELAY_MS="${RENDERER_PROXY_TARGET_DELAY_MS:-350}"
MAX_RENDERER_PROXY_LATE_MS="${MAX_RENDERER_PROXY_LATE_MS:-150}"
MAX_RENDERER_PROXY_LATENCY_MS="${MAX_RENDERER_PROXY_LATENCY_MS:-500}"
MAX_RENDERER_PROXY_LATE_FRAMES="${MAX_RENDERER_PROXY_LATE_FRAMES:-0}"
MAX_RENDERER_PROXY_DROP_FRAMES="${MAX_RENDERER_PROXY_DROP_FRAMES:-0}"
MAX_RENDERER_PROXY_GAP_MS="${MAX_RENDERER_PROXY_GAP_MS:-150}"
SEEDS="${SEEDS:-1 2}"
SCENARIOS="${SCENARIOS:-baseline bandwidth_cliff_recover walking_dead_zone_recover oscillating_edge_recover}"

mkdir -p "${OUTPUT_DIR}"

SDK_ROOT="${SDK_ROOT}" \
WEBRTC_PREFIX="${WEBRTC_PREFIX}" \
OUTPUT_DIR="${OUTPUT_DIR}" \
OUTPUT_BASENAME="webrtc_first_qoe_high_complexity_720p" \
FRAMES="${FRAMES}" \
WIDTH="${WIDTH}" \
HEIGHT="${HEIGHT}" \
START_BITRATE_BPS="${START_BITRATE_BPS}" \
MIN_BITRATE_BPS="${MIN_BITRATE_BPS}" \
MAX_BITRATE_BPS="${MAX_BITRATE_BPS}" \
MIN_PLAYABLE_RATIO="${MIN_PLAYABLE_RATIO}" \
MIN_AVG_PSNR_Y="${MIN_AVG_PSNR_Y}" \
MIN_AVG_SSIM_Y="${MIN_AVG_SSIM_Y}" \
MAX_WEAK_SEND_RPS="${MAX_WEAK_SEND_RPS}" \
MAX_WEAK_RTP_PPS="${MAX_WEAK_RTP_PPS}" \
MAX_WEAK_TARGET_BPS="${MAX_WEAK_TARGET_BPS}" \
MAX_WEAK_ENCODER_FPS="${MAX_WEAK_ENCODER_FPS}" \
MAX_RECOVERY_TIME_MS="${MAX_RECOVERY_TIME_MS}" \
RENDERER_PROXY_TARGET_DELAY_MS="${RENDERER_PROXY_TARGET_DELAY_MS}" \
MAX_RENDERER_PROXY_LATE_MS="${MAX_RENDERER_PROXY_LATE_MS}" \
MAX_RENDERER_PROXY_LATENCY_MS="${MAX_RENDERER_PROXY_LATENCY_MS}" \
MAX_RENDERER_PROXY_LATE_FRAMES="${MAX_RENDERER_PROXY_LATE_FRAMES}" \
MAX_RENDERER_PROXY_DROP_FRAMES="${MAX_RENDERER_PROXY_DROP_FRAMES}" \
MAX_RENDERER_PROXY_GAP_MS="${MAX_RENDERER_PROXY_GAP_MS}" \
SEEDS="${SEEDS}" \
SCENARIOS="${SCENARIOS}" \
CONTENT_MODE=stress \
"${SDK_ROOT}/scripts/run_webrtc_first_ffmpeg_qoe.sh"
